{application,common,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{common_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[common,common_app,common_server,common_sup,my_ssh]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
