{application,pod,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{pod_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[infra_lib,pod_app,pod_lib,pod_server,pod_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
